diff --git a/Dockerfile b/Dockerfile
index f0770dc..3587e94 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4 +4 @@
-FROM alpine:3.6
+FROM debian:stretch
@@ -8,6 +7,0 @@ MAINTAINER Kyle Manna <kyle@kylemanna.com>
-# Testing: pamtester
-RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
-    apk add --update openvpn iptables bash easy-rsa openvpn-auth-pam google-authenticator pamtester && \
-    ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin && \
-    rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*
-
@@ -22,0 +17,9 @@ ENV EASYRSA_CRL_DAYS 3650
+ARG EASYRSA_VERSION=3.0.3
+
+RUN apt-get update \
+ && apt-get install -y openvpn iptables libpam-google-authenticator pamtester curl ca-certificates \
+ && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
+ && mkdir -p ${EASYRSA} \
+ && curl -L https://github.com/OpenVPN/easy-rsa/archive/v${EASYRSA_VERSION}.tar.gz | tar xzf - --strip=2 -C ${EASYRSA} easy-rsa-${EASYRSA_VERSION}/easyrsa3 \
+ && ln -s ${EASYRSA}/easyrsa /usr/local/bin
+
