diff --git a/Dockerfile b/Dockerfile
index 617a7bb..21db25f 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4 +4 @@
-FROM debian:jessie
+FROM debian:stretch
@@ -9 +9 @@ RUN apt-get update && \
-    apt-get install -y openvpn iptables curl && \
+    apt-get install -y openvpn iptables curl ca-certificates && \
